In [2]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('credit_data.csv')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

## Imbalanced 0 = 284315, 1 = 492 not balanced in our data
### 0 ---> Legit Transactions
### 1 ---> Fraudulent Transactions

In [22]:
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [32]:
# separating the legit and fraudulent transactions
legit = df[df['Class']==0]
fraudulent = df[df['Class']==1]

In [36]:
print(legit.shape)
print(fraudulent.shape)

(284315, 31)
(492, 31)

Undersampling

build a sample dataset containing similar distribution of Legit and Fraudulent

Number of Fraudulent Transactions ---> 492 (radomly)

In [43]:
legit_sample = legit.sample(n=492)
legit_sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
190483,128854.0,-0.025797,0.077502,0.878084,0.924585,-0.018931,1.444712,-0.607243,0.497898,0.200899,...,0.312058,0.894685,0.113905,-0.391844,-1.170005,0.876885,0.251212,0.256371,91.17,0
258406,158641.0,1.961897,0.005224,-1.893481,0.207936,1.102956,0.684155,-0.054263,0.198091,0.499058,...,-0.297465,-0.644858,0.397669,-0.656650,-0.444533,0.276965,-0.013210,-0.043262,1.98,0
276535,167154.0,-0.293779,0.313816,0.165903,-0.669512,1.074869,-0.880553,0.569338,0.012941,-0.218274,...,-0.198243,-0.570083,0.099014,-0.419006,-0.451883,0.145645,0.225412,0.092250,2.69,0
246051,153016.0,-1.374632,-0.210410,0.140755,0.082259,1.992276,-1.347423,-0.157619,-0.161568,-0.148389,...,0.214741,1.167222,-0.795716,-0.280032,-0.272076,0.008442,0.486367,0.103859,0.50,0
91714,63595.0,1.178161,-0.060901,-0.308290,0.158543,-0.312313,-1.401071,0.499938,-0.387449,-0.079661,...,-0.008778,-0.194573,-0.144795,0.470547,0.506199,1.063806,-0.131051,0.002927,81.82,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22527,32291.0,-0.269485,0.480377,1.605832,-1.972252,-0.612862,-1.458223,0.513309,-0.198965,0.706693,...,0.018080,0.133470,-0.112780,0.743206,-0.104126,-0.202656,0.067782,0.063926,3.91,0
194351,130546.0,-0.946459,1.561015,1.208416,2.060800,1.960664,0.592813,1.417615,-0.279757,-1.651861,...,-0.364520,-1.121611,-0.329983,0.018961,0.797385,-0.359322,-0.681962,-0.250999,6.05,0
186147,126973.0,-0.045248,1.082639,-0.908456,-1.165599,1.529936,-1.217899,1.669924,-0.415840,-0.504971,...,0.250401,0.921561,-0.219201,0.674015,-0.263011,0.062751,0.395748,0.276600,3.85,0
97926,66442.0,-2.637663,-1.004016,1.102532,0.519366,1.751508,-0.648755,-0.563224,0.923685,-0.637739,...,0.327858,0.117600,-0.362931,-0.295449,0.615633,-0.327841,-0.042474,-0.342319,5.15,0
75071,55886.0,-0.960932,0.099707,0.714640,-2.241170,0.052447,0.273821,-0.289915,0.690408,1.156336,...,0.089464,0.387475,-0.533614,-1.091642,0.754973,-0.402851,0.031002,-0.063193,7.58,0

Concattenate the two DataFrame

In [57]:
new_dataset = pd.concat([legit_sample, fraudulent],axis=0)
new_dataset.shape

(984, 31)

In [59]:
new_dataset['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64